[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:httpd]
command=/usr/sbin/httpd -DFOREGROUND
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:php-fpm]
command=/usr/sbin/php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.out.log
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_backups=5


[program:nrpe]
command=/usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nagios]
command=/usr/sbin/nagios /etc/nagios/nagios.cfg
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
